#include "LogicalInstructions.h"
#include "DataTransferInstructions.cpp"
void MOV(char,char);
void MVI(char,string);
void LDA(string);
void STA(string);
void LHLD(string);
void SHLD(string);
void STAX(char);
void XCHG();
void SPHL();
void XTHL();
void PUSH(char);
void POP(char);
